//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOLX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string catName { get; set; }
        public string desc { get; set; }
        public int price { get; set; }
        public string image { get; set; }
        public string name { get; set; }
        public string add { get; set; }
        public string phone { get; set; }
    
        //public virtual Category Category { get; set; }
    }
}
