//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOLX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Username not provided")]
        public string userName { get; set; }
        [Required(ErrorMessage = "Password not provided")]
        public string pwd { get; set; }

        public string phone { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string email { get; set; }
    }
}
